### ISSUE TITLE
Home button has no use case

### ISSUE THREAD

**Issue by julian31186** [jiechenmc/jiechenmc.github.io#1]
Hello Mr.Chen, after browsing your website I have realized that the home button can only be seen on the home page itself. So if you scroll down to education, there is no way to go back up to home with the button since you would have to manually scroll up anyway

**Comment by jiechenmc** [comment]
The home button was included for purely aesthetic reasons. Thank you for your question and maybe in the future, I will make use of the home button!

**Comment by jiechenmc** [comment]
I have decided to make my bar fixed so it's more functional, thank you for your suggestion!

**Comment by julian31186** [comment]
of course Mr.Chen, have a great night
